### ISSUE TITLE
Allow named clients to be configured from environment

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-docker#3]
In the initial design we separated a default client configured via the environment from named clients configured explicitly. Now I've identified a use case where named clients (sometimes) need to be configured via the environment. E.g. a client "x" is used during development with the env config, but in deployment - with an explicit config pointing to a remote host.

The way this will work is via `type: env` property:

```yaml
docker:
   clients:
      c1:
         maxConnections: 2
         dockerHost: remote-host
      c2:
         type: env
         maxConnections: 2
```
